CREATE DATABASE IF NOT EXISTS watchlist;

USE watchlist;

drop table if EXISTS stockwatchlist;
DROP TABLE IF EXISTS watchlist;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS user;

CREATE TABLE USER (	
	USER_PK INT(10) NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(20) NOT NULL UNIQUE,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (USER_PK)
);

CREATE TABLE STOCK (	
	SYMBOL CHAR(5) NOT NULL UNIQUE,
	NAME VARCHAR(128) NOT NULL,
	CUSIP VARCHAR(11) NOT NULL,
	LASTPRICE DECIMAL (6,2) NOT NULL,
	PRIMARY KEY (SYMBOL)
);

CREATE TABLE WATCHLIST (
	WATCHLIST_PK INT(10) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL,	
	USER_FK INT(10) NOT NULL,			
	PRIMARY KEY (WATCHLIST_PK),
	FOREIGN KEY (USER_FK)
		REFERENCES USER (USER_PK)	
);

CREATE TABLE STOCKWATCHLIST (
	STOCKWATCHLIST_PK INT(10) NOT NULL AUTO_INCREMENT,
	WATCHLIST_FK INT(10) NOT NULL,
	STOCK_SYMBOL CHAR(5),
	PRIMARY KEY (STOCKWATCHLIST_PK),
	FOREIGN KEY (WATCHLIST_FK)
		REFERENCES WATCHLIST (WATCHLIST_PK),
	FOREIGN KEY (STOCK_SYMBOL)
		REFERENCES STOCK (SYMBOL)
);


